# Generated by Django 3.2.4 on 2021-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('detected_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ls', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
