# Generated by Django 3.2.4 on 2021-06-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='ls',
            new_name='det_objects',
        ),
        migrations.AddField(
            model_name='upload',
            name='det_probabilty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
